baseURL: "http://maxieluan.xyz/"
languageCode: en-us
title: My New Hugo Site
theme: theme
languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 2
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 3
        - identifier: contact
          name: Contact
          url: /contact/
          weight: 4
  zh:
    languageName: Chinese
    weight: 2
    menu:
      main:
        - identifier: home
          name: 主页
          url: /zh/
          weight: 1
        - identifier: posts
          name: 文章
          url: /zh/posts/
          weight: 2
        - identifier: 项目
          name: 项目
          url: /zh/projects/
          weight: 3
        - identifier: contact
          name: 联系
          url: /zh/contact/
          weight: 4

